### ISSUE TITLE
Text box wrong horizontal size

### ISSUE THREAD

**Issue by SpiritAxolotl** [SpiritAxolotl/spax.zone#12]
Right now it's a little longer than it should be.
<img width="650" alt="Screen Shot 2022-04-03 at 1 32 06 PM" src="https://user-images.githubusercontent.com/83354374/161444862-c670e30f-3d08-479b-b674-3efb0ac64801.png">
Should be that length if the screen has extra space, and compress if it's smaller.

**Comment by CalmBubbles** [comment]
Is this the size the box should be
![Screenshot_2022_0424_134926](https://user-images.githubusercontent.com/100333110/164958541-bed0ec33-f908-4f11-bdca-ac73f598dbc7.png)

**Comment by CalmBubbles** [comment]
Maybe I'll try to fix this, by launching the actual game with a test site in an iframe

**Comment by CalmBubbles** [comment]
Check [PR 58](https://github.com/SpiritAxolotl/spax.zone/pull/58)   ͡⁠°⁠ ͜⁠ʖ⁠ ͡⁠°

**Comment by SpiritAxolotl** [comment]
okay [commit 98a13da](https://github.com/SpiritAxolotl/spax.zone/commit/98a13da9e9cab87814f86443070b6d17ea91fe95) makes the textboxes as accurate as possible. closing
