### ISSUE TITLE
Whitespace not rendering properly

### ISSUE THREAD

**Issue by SpiritAxolotl** [SpiritAxolotl/spax.zone#40]
Double spaces (or any amount of spaces in a row) get reduced to a single space on the site display. Is there some way to parse it without having it do that?

also I know about "ampersand nbsp" and I don't want to do that everytime

**Comment by CalmBubbles** [comment]
> Double spaces (or any amount of spaces in a row) get reduced to a single space on the site display. Is there some way to parse it without having it do that?
> 
> also I know about "ampersand nbsp" and I don't want to do that everytime

Use the html [`pre`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre) tag to preserve whitespaces

**Comment by mathew27700** [comment]
Add `white-space: pre-wrap;` to your css for a more global solution

**Comment by SpiritAxolotl** [comment]
oh wait I just realized why this is

the [white-space](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) css property would fix this
