### ISSUE TITLE
background isn't at visual 100% height

### ISSUE THREAD

**Issue by SpiritAxolotl** [SpiritAxolotl/spax.zone#54]
currently being tested in <https://github.com/SpiritAxolotl/spax.zone/tree/marbelyn-patch-5>

height is fixed and is either too long or too short
<img width="1440" alt="Screenshot 2024-03-04 at 9 57 30 PM" src="https://github.com/SpiritAxolotl/spax.zone/assets/83354374/cd93add8-920a-43fb-b7fb-fefbc03bcf68">
<img width="1440" alt="Screenshot 2024-03-04 at 9 58 48 PM" src="https://github.com/SpiritAxolotl/spax.zone/assets/83354374/591bea38-cf58-4537-be51-76bc4bbbaf06">

**Comment by SpiritAxolotl** [comment]
@marbelynrye

**Comment by SpiritAxolotl** [comment]
the first page was main.html and the second was alldepfaces.html, but the issue is prevalent on any page with the experimental css

**Comment by Luamnoxu** [comment]
im gonna need some more details on where and what is wrong, going to /html/main.html myself this is not true and works as intended

**Comment by SpiritAxolotl** [comment]
@Luamnoxu I didn't push the changes to the main branch. like I said at the top it's only on the marbelyn branch

**Comment by SpiritAxolotl** [comment]
I've given up on this. my site doesn't need parallax background though
