### ISSUE TITLE
bug on `/tests/ooo`

### ISSUE THREAD

**Issue by KwiatekMiki** [SpiritAxolotl/spax.zone#55]
![image](https://github.com/SpiritAxolotl/spax.zone/assets/79092746/f1b1c708-d56a-4a95-a424-f2599ab253c4)

**Comment by SpiritAxolotl** [comment]
fuck

**Comment by SpiritAxolotl** [comment]
```diff
-o(mod(get(), 63)-1);
+o(mod(get()-2, 63)+1);
```
modulo is so fucky when it's a range above 0
